// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package gitlab

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-gitlab/sdk/v9/go/gitlab/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The `IntegrationGithub` resource manages the lifecycle of a project integration with GitHub.
//
// > This resource requires a GitLab Enterprise instance.
//
// > This resource is deprecated and will be removed in 19.0. Use `ProjectIntegrationGithub` instead.
//
// **Upstream API**: [GitLab REST API docs](https://docs.gitlab.com/api/project_integrations/#github)
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-gitlab/sdk/v9/go/gitlab"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			awesomeProject, err := gitlab.NewProject(ctx, "awesome_project", &gitlab.ProjectArgs{
//				Name:            pulumi.String("awesome_project"),
//				Description:     pulumi.String("My awesome project."),
//				VisibilityLevel: pulumi.String("public"),
//			})
//			if err != nil {
//				return err
//			}
//			_, err = gitlab.NewIntegrationGithub(ctx, "github", &gitlab.IntegrationGithubArgs{
//				Project:       awesomeProject.ID(),
//				Token:         pulumi.String("REDACTED"),
//				RepositoryUrl: pulumi.String("https://github.com/gitlabhq/terraform-provider-gitlab"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Starting in Terraform v1.5.0, you can use an import block to import `gitlab_integration_github`. For example:
//
// terraform
//
// import {
//
//	to = gitlab_integration_github.example
//
//	id = "see CLI command below for ID"
//
// }
//
// Importing using the CLI is supported with the following syntax:
//
// ```sh
// $ pulumi import gitlab:index/integrationGithub:IntegrationGithub You can import a gitlab_integration_github state using `<resource> <project_id>`:
// ```
//
// ```sh
// $ pulumi import gitlab:index/integrationGithub:IntegrationGithub github 1
// ```
type IntegrationGithub struct {
	pulumi.CustomResourceState

	// Whether the integration is active.
	Active pulumi.BoolOutput `pulumi:"active"`
	// Creation time.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// ID of the project you want to activate the integration on.
	Project       pulumi.StringOutput `pulumi:"project"`
	RepositoryUrl pulumi.StringOutput `pulumi:"repositoryUrl"`
	// Append the instance name instead of the branch to the status. Must enable to set a GitLab status check as *required* in GitHub. See [Static / dynamic status check names] to learn more.
	StaticContext pulumi.BoolPtrOutput `pulumi:"staticContext"`
	// The title of this resource.
	Title pulumi.StringOutput `pulumi:"title"`
	// A GitHub personal access token with at least the `repo:status` scope.
	Token pulumi.StringOutput `pulumi:"token"`
	// Update time.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewIntegrationGithub registers a new resource with the given unique name, arguments, and options.
func NewIntegrationGithub(ctx *pulumi.Context,
	name string, args *IntegrationGithubArgs, opts ...pulumi.ResourceOption) (*IntegrationGithub, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	if args.RepositoryUrl == nil {
		return nil, errors.New("invalid value for required argument 'RepositoryUrl'")
	}
	if args.Token == nil {
		return nil, errors.New("invalid value for required argument 'Token'")
	}
	if args.Token != nil {
		args.Token = pulumi.ToSecret(args.Token).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource IntegrationGithub
	err := ctx.RegisterResource("gitlab:index/integrationGithub:IntegrationGithub", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIntegrationGithub gets an existing IntegrationGithub resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIntegrationGithub(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IntegrationGithubState, opts ...pulumi.ResourceOption) (*IntegrationGithub, error) {
	var resource IntegrationGithub
	err := ctx.ReadResource("gitlab:index/integrationGithub:IntegrationGithub", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IntegrationGithub resources.
type integrationGithubState struct {
	// Whether the integration is active.
	Active *bool `pulumi:"active"`
	// Creation time.
	CreatedAt *string `pulumi:"createdAt"`
	// ID of the project you want to activate the integration on.
	Project       *string `pulumi:"project"`
	RepositoryUrl *string `pulumi:"repositoryUrl"`
	// Append the instance name instead of the branch to the status. Must enable to set a GitLab status check as *required* in GitHub. See [Static / dynamic status check names] to learn more.
	StaticContext *bool `pulumi:"staticContext"`
	// The title of this resource.
	Title *string `pulumi:"title"`
	// A GitHub personal access token with at least the `repo:status` scope.
	Token *string `pulumi:"token"`
	// Update time.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type IntegrationGithubState struct {
	// Whether the integration is active.
	Active pulumi.BoolPtrInput
	// Creation time.
	CreatedAt pulumi.StringPtrInput
	// ID of the project you want to activate the integration on.
	Project       pulumi.StringPtrInput
	RepositoryUrl pulumi.StringPtrInput
	// Append the instance name instead of the branch to the status. Must enable to set a GitLab status check as *required* in GitHub. See [Static / dynamic status check names] to learn more.
	StaticContext pulumi.BoolPtrInput
	// The title of this resource.
	Title pulumi.StringPtrInput
	// A GitHub personal access token with at least the `repo:status` scope.
	Token pulumi.StringPtrInput
	// Update time.
	UpdatedAt pulumi.StringPtrInput
}

func (IntegrationGithubState) ElementType() reflect.Type {
	return reflect.TypeOf((*integrationGithubState)(nil)).Elem()
}

type integrationGithubArgs struct {
	// ID of the project you want to activate the integration on.
	Project       string `pulumi:"project"`
	RepositoryUrl string `pulumi:"repositoryUrl"`
	// Append the instance name instead of the branch to the status. Must enable to set a GitLab status check as *required* in GitHub. See [Static / dynamic status check names] to learn more.
	StaticContext *bool `pulumi:"staticContext"`
	// A GitHub personal access token with at least the `repo:status` scope.
	Token string `pulumi:"token"`
}

// The set of arguments for constructing a IntegrationGithub resource.
type IntegrationGithubArgs struct {
	// ID of the project you want to activate the integration on.
	Project       pulumi.StringInput
	RepositoryUrl pulumi.StringInput
	// Append the instance name instead of the branch to the status. Must enable to set a GitLab status check as *required* in GitHub. See [Static / dynamic status check names] to learn more.
	StaticContext pulumi.BoolPtrInput
	// A GitHub personal access token with at least the `repo:status` scope.
	Token pulumi.StringInput
}

func (IntegrationGithubArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*integrationGithubArgs)(nil)).Elem()
}

type IntegrationGithubInput interface {
	pulumi.Input

	ToIntegrationGithubOutput() IntegrationGithubOutput
	ToIntegrationGithubOutputWithContext(ctx context.Context) IntegrationGithubOutput
}

func (*IntegrationGithub) ElementType() reflect.Type {
	return reflect.TypeOf((**IntegrationGithub)(nil)).Elem()
}

func (i *IntegrationGithub) ToIntegrationGithubOutput() IntegrationGithubOutput {
	return i.ToIntegrationGithubOutputWithContext(context.Background())
}

func (i *IntegrationGithub) ToIntegrationGithubOutputWithContext(ctx context.Context) IntegrationGithubOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IntegrationGithubOutput)
}

// IntegrationGithubArrayInput is an input type that accepts IntegrationGithubArray and IntegrationGithubArrayOutput values.
// You can construct a concrete instance of `IntegrationGithubArrayInput` via:
//
//	IntegrationGithubArray{ IntegrationGithubArgs{...} }
type IntegrationGithubArrayInput interface {
	pulumi.Input

	ToIntegrationGithubArrayOutput() IntegrationGithubArrayOutput
	ToIntegrationGithubArrayOutputWithContext(context.Context) IntegrationGithubArrayOutput
}

type IntegrationGithubArray []IntegrationGithubInput

func (IntegrationGithubArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IntegrationGithub)(nil)).Elem()
}

func (i IntegrationGithubArray) ToIntegrationGithubArrayOutput() IntegrationGithubArrayOutput {
	return i.ToIntegrationGithubArrayOutputWithContext(context.Background())
}

func (i IntegrationGithubArray) ToIntegrationGithubArrayOutputWithContext(ctx context.Context) IntegrationGithubArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IntegrationGithubArrayOutput)
}

// IntegrationGithubMapInput is an input type that accepts IntegrationGithubMap and IntegrationGithubMapOutput values.
// You can construct a concrete instance of `IntegrationGithubMapInput` via:
//
//	IntegrationGithubMap{ "key": IntegrationGithubArgs{...} }
type IntegrationGithubMapInput interface {
	pulumi.Input

	ToIntegrationGithubMapOutput() IntegrationGithubMapOutput
	ToIntegrationGithubMapOutputWithContext(context.Context) IntegrationGithubMapOutput
}

type IntegrationGithubMap map[string]IntegrationGithubInput

func (IntegrationGithubMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IntegrationGithub)(nil)).Elem()
}

func (i IntegrationGithubMap) ToIntegrationGithubMapOutput() IntegrationGithubMapOutput {
	return i.ToIntegrationGithubMapOutputWithContext(context.Background())
}

func (i IntegrationGithubMap) ToIntegrationGithubMapOutputWithContext(ctx context.Context) IntegrationGithubMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IntegrationGithubMapOutput)
}

type IntegrationGithubOutput struct{ *pulumi.OutputState }

func (IntegrationGithubOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IntegrationGithub)(nil)).Elem()
}

func (o IntegrationGithubOutput) ToIntegrationGithubOutput() IntegrationGithubOutput {
	return o
}

func (o IntegrationGithubOutput) ToIntegrationGithubOutputWithContext(ctx context.Context) IntegrationGithubOutput {
	return o
}

// Whether the integration is active.
func (o IntegrationGithubOutput) Active() pulumi.BoolOutput {
	return o.ApplyT(func(v *IntegrationGithub) pulumi.BoolOutput { return v.Active }).(pulumi.BoolOutput)
}

// Creation time.
func (o IntegrationGithubOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *IntegrationGithub) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// ID of the project you want to activate the integration on.
func (o IntegrationGithubOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *IntegrationGithub) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

func (o IntegrationGithubOutput) RepositoryUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *IntegrationGithub) pulumi.StringOutput { return v.RepositoryUrl }).(pulumi.StringOutput)
}

// Append the instance name instead of the branch to the status. Must enable to set a GitLab status check as *required* in GitHub. See [Static / dynamic status check names] to learn more.
func (o IntegrationGithubOutput) StaticContext() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IntegrationGithub) pulumi.BoolPtrOutput { return v.StaticContext }).(pulumi.BoolPtrOutput)
}

// The title of this resource.
func (o IntegrationGithubOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v *IntegrationGithub) pulumi.StringOutput { return v.Title }).(pulumi.StringOutput)
}

// A GitHub personal access token with at least the `repo:status` scope.
func (o IntegrationGithubOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *IntegrationGithub) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

// Update time.
func (o IntegrationGithubOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *IntegrationGithub) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type IntegrationGithubArrayOutput struct{ *pulumi.OutputState }

func (IntegrationGithubArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IntegrationGithub)(nil)).Elem()
}

func (o IntegrationGithubArrayOutput) ToIntegrationGithubArrayOutput() IntegrationGithubArrayOutput {
	return o
}

func (o IntegrationGithubArrayOutput) ToIntegrationGithubArrayOutputWithContext(ctx context.Context) IntegrationGithubArrayOutput {
	return o
}

func (o IntegrationGithubArrayOutput) Index(i pulumi.IntInput) IntegrationGithubOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *IntegrationGithub {
		return vs[0].([]*IntegrationGithub)[vs[1].(int)]
	}).(IntegrationGithubOutput)
}

type IntegrationGithubMapOutput struct{ *pulumi.OutputState }

func (IntegrationGithubMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IntegrationGithub)(nil)).Elem()
}

func (o IntegrationGithubMapOutput) ToIntegrationGithubMapOutput() IntegrationGithubMapOutput {
	return o
}

func (o IntegrationGithubMapOutput) ToIntegrationGithubMapOutputWithContext(ctx context.Context) IntegrationGithubMapOutput {
	return o
}

func (o IntegrationGithubMapOutput) MapIndex(k pulumi.StringInput) IntegrationGithubOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *IntegrationGithub {
		return vs[0].(map[string]*IntegrationGithub)[vs[1].(string)]
	}).(IntegrationGithubOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IntegrationGithubInput)(nil)).Elem(), &IntegrationGithub{})
	pulumi.RegisterInputType(reflect.TypeOf((*IntegrationGithubArrayInput)(nil)).Elem(), IntegrationGithubArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*IntegrationGithubMapInput)(nil)).Elem(), IntegrationGithubMap{})
	pulumi.RegisterOutputType(IntegrationGithubOutput{})
	pulumi.RegisterOutputType(IntegrationGithubArrayOutput{})
	pulumi.RegisterOutputType(IntegrationGithubMapOutput{})
}
