provider: gitlab
major-version: 6
upstreamProviderOrg: gitlabhq
env:
  PULUMI_GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
makeTemplate: bridged
team: ecosystem
plugins:
  - name: local
    version: "0.0.1"
