provider: gitlab
major-version: 9
upstreamProviderOrg: gitlabhq
esc:
  enabled: true
env:
  PULUMI_GITLAB_TOKEN: ${{ secrets.PULUMI_GITLAB_TOKEN }}
makeTemplate: bridged
team: ecosystem
plugins:
  - name: std
    version: "1.6.2"
  - name: terraform
    version: "1.0.16"
    kind: converter
  - name: local
    version: "0.0.1"
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
