provider: gitlab
major-version: 6
upstreamProviderOrg: gitlabhq
env:
  PULUMI_GITLAB_TOKEN: ${{ secrets.PULUMI_GITLAB_TOKEN }}
makeTemplate: bridged
team: ecosystem
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter

  - name: local
    version: "0.0.1"

actions:
  preTest:
    - name: make upstream
      run: |
        make upstream
    - name: Run provider tests
      run: |
        cd provider && go test -v -json -count=1 -cover -timeout 2h -tags=${{ matrix.language }} -parallel 4 . 2>&1 | tee /tmp/gotest.log | gotestfmt
pulumiConvert: 1
