// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GitLab
{
    /// <summary>
    /// The `gitlab.ProjectApprovalRules` resource manages the complete set of approval rules of a project.
    /// 
    /// &gt; This resource requires a GitLab Enterprise instance.
    /// 
    /// &gt; This resource is authoritative: it manages the *entire* set of a project's approval rules. Any approval
    /// rule that exists on the project but is not declared in the configuration will be **deleted**, and such deletions
    /// are shown in the plan. If you only need to manage individual rules additively, use the
    /// `gitlab.ProjectApprovalRule` resource instead.
    /// 
    /// &gt; **Managing the `AnyApprover` rule.** A project may have **at most one** rule with
    /// `RuleType = "AnyApprover"` (the "all eligible users" rule), and GitLab does not require it to carry
    /// any particular name. This resource therefore matches it by `RuleType` rather than by name, so its
    /// name can be chosen freely. A newly created project has no approval rules at all; if you do not declare an
    /// `AnyApprover` rule, none is created, and one that already exists is deleted like any other undeclared
    /// rule.
    /// 
    /// &gt; Conflicts with the use of `gitlab.ProjectApprovalRule` when used on the same project. Use one or the other to ensure the desired state.
    /// 
    /// **Upstream API**: [GitLab REST API docs](https://docs.gitlab.com/api/merge_request_approvals/#approval-rules-for-projects)
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using GitLab = Pulumi.GitLab;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // This resource is authoritative: it manages the *complete* set of a project's approval rules.
    ///     // Any approval rule that exists on the project but is not declared below is deleted.
    ///     var example = new GitLab.ProjectApprovalRules("example", new()
    ///     {
    ///         Project = "42",
    ///         ApprovalRules = new[]
    ///         {
    ///             new GitLab.Inputs.ProjectApprovalRulesApprovalRuleArgs
    ///             {
    ///                 Name = "All eligible users",
    ///                 RuleType = "any_approver",
    ///                 ApprovalsRequired = 0,
    ///             },
    ///             new GitLab.Inputs.ProjectApprovalRulesApprovalRuleArgs
    ///             {
    ///                 Name = "Security",
    ///                 ApprovalsRequired = 2,
    ///                 RuleType = "regular",
    ///                 UserIds = new[]
    ///                 {
    ///                     50,
    ///                     51,
    ///                 },
    ///                 GroupIds = new[]
    ///                 {
    ///                     60,
    ///                 },
    ///             },
    ///             new GitLab.Inputs.ProjectApprovalRulesApprovalRuleArgs
    ///             {
    ///                 Name = "Release managers",
    ///                 ApprovalsRequired = 1,
    ///                 RuleType = "regular",
    ///                 GroupIds = new[]
    ///                 {
    ///                     70,
    ///                 },
    ///                 AppliesToAllProtectedBranches = true,
    ///             },
    ///             new GitLab.Inputs.ProjectApprovalRulesApprovalRuleArgs
    ///             {
    ///                 Name = "Coverage-Check",
    ///                 ApprovalsRequired = 1,
    ///                 RuleType = "report_approver",
    ///                 ReportType = "code_coverage",
    ///                 UserIds = new[]
    ///                 {
    ///                     50,
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Starting in Terraform v1.5.0, you can use an import block to import `gitlab.ProjectApprovalRules`. For example:
    /// 
    /// Importing using the CLI is supported with the following syntax:
    /// 
    /// A project's approval rules can be imported using the project ID or full path, e.g.
    /// 
    /// ```sh
    /// $ pulumi import gitlab:index/projectApprovalRules:ProjectApprovalRules example "42"
    /// ```
    /// 
    /// or
    /// 
    /// ```sh
    /// $ pulumi import gitlab:index/projectApprovalRules:ProjectApprovalRules example "my-group/my-project"
    /// ```
    /// </summary>
    [GitLabResourceType("gitlab:index/projectApprovalRules:ProjectApprovalRules")]
    public partial class ProjectApprovalRules : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The complete set of approval rules of the project. Declaring an empty set removes every approval rule from the project.
        /// </summary>
        [Output("approvalRules")]
        public Output<ImmutableArray<Outputs.ProjectApprovalRulesApprovalRule>> ApprovalRules { get; private set; } = null!;

        /// <summary>
        /// The ID or full path of the project.
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;


        /// <summary>
        /// Create a ProjectApprovalRules resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ProjectApprovalRules(string name, ProjectApprovalRulesArgs args, CustomResourceOptions? options = null)
            : base("gitlab:index/projectApprovalRules:ProjectApprovalRules", name, args ?? new ProjectApprovalRulesArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ProjectApprovalRules(string name, Input<string> id, ProjectApprovalRulesState? state = null, CustomResourceOptions? options = null)
            : base("gitlab:index/projectApprovalRules:ProjectApprovalRules", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ProjectApprovalRules resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ProjectApprovalRules Get(string name, Input<string> id, ProjectApprovalRulesState? state = null, CustomResourceOptions? options = null)
        {
            return new ProjectApprovalRules(name, id, state, options);
        }
    }

    public sealed class ProjectApprovalRulesArgs : global::Pulumi.ResourceArgs
    {
        [Input("approvalRules", required: true)]
        private InputList<Inputs.ProjectApprovalRulesApprovalRuleArgs>? _approvalRules;

        /// <summary>
        /// The complete set of approval rules of the project. Declaring an empty set removes every approval rule from the project.
        /// </summary>
        public InputList<Inputs.ProjectApprovalRulesApprovalRuleArgs> ApprovalRules
        {
            get => _approvalRules ?? (_approvalRules = new InputList<Inputs.ProjectApprovalRulesApprovalRuleArgs>());
            set => _approvalRules = value;
        }

        /// <summary>
        /// The ID or full path of the project.
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        public ProjectApprovalRulesArgs()
        {
        }
        public static new ProjectApprovalRulesArgs Empty => new ProjectApprovalRulesArgs();
    }

    public sealed class ProjectApprovalRulesState : global::Pulumi.ResourceArgs
    {
        [Input("approvalRules")]
        private InputList<Inputs.ProjectApprovalRulesApprovalRuleGetArgs>? _approvalRules;

        /// <summary>
        /// The complete set of approval rules of the project. Declaring an empty set removes every approval rule from the project.
        /// </summary>
        public InputList<Inputs.ProjectApprovalRulesApprovalRuleGetArgs> ApprovalRules
        {
            get => _approvalRules ?? (_approvalRules = new InputList<Inputs.ProjectApprovalRulesApprovalRuleGetArgs>());
            set => _approvalRules = value;
        }

        /// <summary>
        /// The ID or full path of the project.
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        public ProjectApprovalRulesState()
        {
        }
        public static new ProjectApprovalRulesState Empty => new ProjectApprovalRulesState();
    }
}
