// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gitlab.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class GetRunnerControllerScopesPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRunnerControllerScopesPlainArgs Empty = new GetRunnerControllerScopesPlainArgs();

    /**
     * The ID of the runner controller.
     * 
     */
    @Import(name="runnerControllerId", required=true)
    private Integer runnerControllerId;

    /**
     * @return The ID of the runner controller.
     * 
     */
    public Integer runnerControllerId() {
        return this.runnerControllerId;
    }

    private GetRunnerControllerScopesPlainArgs() {}

    private GetRunnerControllerScopesPlainArgs(GetRunnerControllerScopesPlainArgs $) {
        this.runnerControllerId = $.runnerControllerId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRunnerControllerScopesPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRunnerControllerScopesPlainArgs $;

        public Builder() {
            $ = new GetRunnerControllerScopesPlainArgs();
        }

        public Builder(GetRunnerControllerScopesPlainArgs defaults) {
            $ = new GetRunnerControllerScopesPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param runnerControllerId The ID of the runner controller.
         * 
         * @return builder
         * 
         */
        public Builder runnerControllerId(Integer runnerControllerId) {
            $.runnerControllerId = runnerControllerId;
            return this;
        }

        public GetRunnerControllerScopesPlainArgs build() {
            if ($.runnerControllerId == null) {
                throw new MissingRequiredPropertyException("GetRunnerControllerScopesPlainArgs", "runnerControllerId");
            }
            return $;
        }
    }

}
