// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gitlab.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.util.Objects;


public final class GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs extends com.pulumi.resources.ResourceArgs {

    public static final GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs Empty = new GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs();

    /**
     * Allow (true) or prevent (false) the use of skip-ci directive.
     * 
     */
    @Import(name="allowed", required=true)
    private Output<Boolean> allowed;

    /**
     * @return Allow (true) or prevent (false) the use of skip-ci directive.
     * 
     */
    public Output<Boolean> allowed() {
        return this.allowed;
    }

    private GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs() {}

    private GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs(GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs $) {
        this.allowed = $.allowed;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs $;

        public Builder() {
            $ = new GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs();
        }

        public Builder(GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs defaults) {
            $ = new GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param allowed Allow (true) or prevent (false) the use of skip-ci directive.
         * 
         * @return builder
         * 
         */
        public Builder allowed(Output<Boolean> allowed) {
            $.allowed = allowed;
            return this;
        }

        /**
         * @param allowed Allow (true) or prevent (false) the use of skip-ci directive.
         * 
         * @return builder
         * 
         */
        public Builder allowed(Boolean allowed) {
            return allowed(Output.of(allowed));
        }

        public GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs build() {
            if ($.allowed == null) {
                throw new MissingRequiredPropertyException("GetSecurityPolicyDocumentScanExecutionPolicySkipCiArgs", "allowed");
            }
            return $;
        }
    }

}
