// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.gitlab.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ReleaseAssetsArgs extends com.pulumi.resources.ResourceArgs {

    public static final ReleaseAssetsArgs Empty = new ReleaseAssetsArgs();

    /**
     * The total count of assets in this release.
     * 
     */
    @Import(name="count")
    private @Nullable Output<Integer> count;

    /**
     * @return The total count of assets in this release.
     * 
     */
    public Optional<Output<Integer>> count() {
        return Optional.ofNullable(this.count);
    }

    private ReleaseAssetsArgs() {}

    private ReleaseAssetsArgs(ReleaseAssetsArgs $) {
        this.count = $.count;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ReleaseAssetsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ReleaseAssetsArgs $;

        public Builder() {
            $ = new ReleaseAssetsArgs();
        }

        public Builder(ReleaseAssetsArgs defaults) {
            $ = new ReleaseAssetsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param count The total count of assets in this release.
         * 
         * @return builder
         * 
         */
        public Builder count(@Nullable Output<Integer> count) {
            $.count = count;
            return this;
        }

        /**
         * @param count The total count of assets in this release.
         * 
         * @return builder
         * 
         */
        public Builder count(Integer count) {
            return count(Output.of(count));
        }

        public ReleaseAssetsArgs build() {
            return $;
        }
    }

}
