// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GitLab.Outputs
{

    [OutputType]
    public sealed class GetSecurityPolicyDocumentScanExecutionPolicyPolicyScopeProjectsResult
    {
        /// <summary>
        /// List of project IDs to exclude from this policy.
        /// </summary>
        public readonly ImmutableArray<int> Excludings;
        /// <summary>
        /// List of project IDs to explicitly include in this policy.
        /// </summary>
        public readonly ImmutableArray<int> Includings;

        [OutputConstructor]
        private GetSecurityPolicyDocumentScanExecutionPolicyPolicyScopeProjectsResult(
            ImmutableArray<int> excludings,

            ImmutableArray<int> includings)
        {
            Excludings = excludings;
            Includings = includings;
        }
    }
}
