// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GitLab.Outputs
{

    [OutputType]
    public sealed class GetUserSshkeysKeyResult
    {
        public readonly string CreatedAt;
        public readonly string ExpiresAt;
        public readonly string Key;
        public readonly int KeyId;
        public readonly string Title;
        /// <summary>
        /// ID of the user to get the SSH keys for.
        /// </summary>
        public readonly int UserId;

        [OutputConstructor]
        private GetUserSshkeysKeyResult(
            string createdAt,

            string expiresAt,

            string key,

            int keyId,

            string title,

            int userId)
        {
            CreatedAt = createdAt;
            ExpiresAt = expiresAt;
            Key = key;
            KeyId = keyId;
            Title = title;
            UserId = userId;
        }
    }
}
