# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ProjectContainerTagProtectionArgs', 'ProjectContainerTagProtection']

@pulumi.input_type
class ProjectContainerTagProtectionArgs:
    def __init__(__self__, *,
                 project: pulumi.Input[_builtins.str],
                 tag_name_regex: pulumi.Input[_builtins.str],
                 immutable: Optional[pulumi.Input[_builtins.bool]] = None,
                 minimum_access_level_for_delete: Optional[pulumi.Input[_builtins.str]] = None,
                 minimum_access_level_for_push: Optional[pulumi.Input[_builtins.str]] = None,
                 timeouts: Optional[pulumi.Input['ProjectContainerTagProtectionTimeoutsArgs']] = None):
        """
        The set of arguments for constructing a ProjectContainerTagProtection resource.

        :param pulumi.Input[_builtins.str] project: ID or URL-encoded path of the project.
        :param pulumi.Input[_builtins.str] tag_name_regex: Container tag path pattern protected by the protection rule. Wildcard character * allowed. Tag path pattern should start with the project's full path.
        :param pulumi.Input[_builtins.bool] immutable: Whether the container tag is immutable. If set, the container tag cannot be deleted or overwritten. Conflicts with `minimum_access_level_for_push` and `minimum_access_level_for_delete`.
        :param pulumi.Input[_builtins.str] minimum_access_level_for_delete: Minimum GitLab access level required to delete protected container tags in the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        :param pulumi.Input[_builtins.str] minimum_access_level_for_push: Minimum GitLab access level required to push protected container tags to the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        """
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "tag_name_regex", tag_name_regex)
        if immutable is not None:
            pulumi.set(__self__, "immutable", immutable)
        if minimum_access_level_for_delete is not None:
            pulumi.set(__self__, "minimum_access_level_for_delete", minimum_access_level_for_delete)
        if minimum_access_level_for_push is not None:
            pulumi.set(__self__, "minimum_access_level_for_push", minimum_access_level_for_push)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Input[_builtins.str]:
        """
        ID or URL-encoded path of the project.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter(name="tagNameRegex")
    def tag_name_regex(self) -> pulumi.Input[_builtins.str]:
        """
        Container tag path pattern protected by the protection rule. Wildcard character * allowed. Tag path pattern should start with the project's full path.
        """
        return pulumi.get(self, "tag_name_regex")

    @tag_name_regex.setter
    def tag_name_regex(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "tag_name_regex", value)

    @_builtins.property
    @pulumi.getter
    def immutable(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the container tag is immutable. If set, the container tag cannot be deleted or overwritten. Conflicts with `minimum_access_level_for_push` and `minimum_access_level_for_delete`.
        """
        return pulumi.get(self, "immutable")

    @immutable.setter
    def immutable(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "immutable", value)

    @_builtins.property
    @pulumi.getter(name="minimumAccessLevelForDelete")
    def minimum_access_level_for_delete(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Minimum GitLab access level required to delete protected container tags in the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        """
        return pulumi.get(self, "minimum_access_level_for_delete")

    @minimum_access_level_for_delete.setter
    def minimum_access_level_for_delete(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "minimum_access_level_for_delete", value)

    @_builtins.property
    @pulumi.getter(name="minimumAccessLevelForPush")
    def minimum_access_level_for_push(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Minimum GitLab access level required to push protected container tags to the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        """
        return pulumi.get(self, "minimum_access_level_for_push")

    @minimum_access_level_for_push.setter
    def minimum_access_level_for_push(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "minimum_access_level_for_push", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['ProjectContainerTagProtectionTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['ProjectContainerTagProtectionTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)


@pulumi.input_type
class _ProjectContainerTagProtectionState:
    def __init__(__self__, *,
                 immutable: Optional[pulumi.Input[_builtins.bool]] = None,
                 minimum_access_level_for_delete: Optional[pulumi.Input[_builtins.str]] = None,
                 minimum_access_level_for_push: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 protection_rule_id: Optional[pulumi.Input[_builtins.int]] = None,
                 tag_name_regex: Optional[pulumi.Input[_builtins.str]] = None,
                 timeouts: Optional[pulumi.Input['ProjectContainerTagProtectionTimeoutsArgs']] = None):
        """
        Input properties used for looking up and filtering ProjectContainerTagProtection resources.

        :param pulumi.Input[_builtins.bool] immutable: Whether the container tag is immutable. If set, the container tag cannot be deleted or overwritten. Conflicts with `minimum_access_level_for_push` and `minimum_access_level_for_delete`.
        :param pulumi.Input[_builtins.str] minimum_access_level_for_delete: Minimum GitLab access level required to delete protected container tags in the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        :param pulumi.Input[_builtins.str] minimum_access_level_for_push: Minimum GitLab access level required to push protected container tags to the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        :param pulumi.Input[_builtins.str] project: ID or URL-encoded path of the project.
        :param pulumi.Input[_builtins.int] protection_rule_id: Unique ID of the protection rule.
        :param pulumi.Input[_builtins.str] tag_name_regex: Container tag path pattern protected by the protection rule. Wildcard character * allowed. Tag path pattern should start with the project's full path.
        """
        if immutable is not None:
            pulumi.set(__self__, "immutable", immutable)
        if minimum_access_level_for_delete is not None:
            pulumi.set(__self__, "minimum_access_level_for_delete", minimum_access_level_for_delete)
        if minimum_access_level_for_push is not None:
            pulumi.set(__self__, "minimum_access_level_for_push", minimum_access_level_for_push)
        if project is not None:
            pulumi.set(__self__, "project", project)
        if protection_rule_id is not None:
            pulumi.set(__self__, "protection_rule_id", protection_rule_id)
        if tag_name_regex is not None:
            pulumi.set(__self__, "tag_name_regex", tag_name_regex)
        if timeouts is not None:
            pulumi.set(__self__, "timeouts", timeouts)

    @_builtins.property
    @pulumi.getter
    def immutable(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the container tag is immutable. If set, the container tag cannot be deleted or overwritten. Conflicts with `minimum_access_level_for_push` and `minimum_access_level_for_delete`.
        """
        return pulumi.get(self, "immutable")

    @immutable.setter
    def immutable(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "immutable", value)

    @_builtins.property
    @pulumi.getter(name="minimumAccessLevelForDelete")
    def minimum_access_level_for_delete(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Minimum GitLab access level required to delete protected container tags in the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        """
        return pulumi.get(self, "minimum_access_level_for_delete")

    @minimum_access_level_for_delete.setter
    def minimum_access_level_for_delete(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "minimum_access_level_for_delete", value)

    @_builtins.property
    @pulumi.getter(name="minimumAccessLevelForPush")
    def minimum_access_level_for_push(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Minimum GitLab access level required to push protected container tags to the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        """
        return pulumi.get(self, "minimum_access_level_for_push")

    @minimum_access_level_for_push.setter
    def minimum_access_level_for_push(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "minimum_access_level_for_push", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        ID or URL-encoded path of the project.
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter(name="protectionRuleId")
    def protection_rule_id(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Unique ID of the protection rule.
        """
        return pulumi.get(self, "protection_rule_id")

    @protection_rule_id.setter
    def protection_rule_id(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "protection_rule_id", value)

    @_builtins.property
    @pulumi.getter(name="tagNameRegex")
    def tag_name_regex(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Container tag path pattern protected by the protection rule. Wildcard character * allowed. Tag path pattern should start with the project's full path.
        """
        return pulumi.get(self, "tag_name_regex")

    @tag_name_regex.setter
    def tag_name_regex(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "tag_name_regex", value)

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> Optional[pulumi.Input['ProjectContainerTagProtectionTimeoutsArgs']]:
        return pulumi.get(self, "timeouts")

    @timeouts.setter
    def timeouts(self, value: Optional[pulumi.Input['ProjectContainerTagProtectionTimeoutsArgs']]):
        pulumi.set(self, "timeouts", value)


@pulumi.type_token("gitlab:index/projectContainerTagProtection:ProjectContainerTagProtection")
class ProjectContainerTagProtection(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 immutable: Optional[pulumi.Input[_builtins.bool]] = None,
                 minimum_access_level_for_delete: Optional[pulumi.Input[_builtins.str]] = None,
                 minimum_access_level_for_push: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 tag_name_regex: Optional[pulumi.Input[_builtins.str]] = None,
                 timeouts: Optional[pulumi.Input[Union['ProjectContainerTagProtectionTimeoutsArgs', 'ProjectContainerTagProtectionTimeoutsArgsDict']]] = None,
                 __props__=None):
        """
        The `ProjectContainerTagProtection` resource allows managing the lifecycle of a container tag protection rule.

        You can use a regular expression to protect multiple container tags with the same container protection rule.
        You have to **either set** (both options are mutually exclusive):

        - Only `immutable = true` which allows any user with `developer` role to create tags matching the regex but makes the object unchangeable once pushed ;
        - Both `minimum_access_level_for_push` and `minimum_access_level_for_delete` attributes to mark the container tag as mutable only with regards to the given access levels.

        **Upstream API**: [GitLab GraphQL API documentation](https://docs.gitlab.com/api/graphql/reference/#mutationcreatecontainerprotectiontagrule)

        **Protected tags**: [General documentation](https://docs.gitlab.com/user/packages/container_registry/protected_container_tags/)

        **Immutable tags**: [General documentation](https://docs.gitlab.com/user/packages/container_registry/immutable_container_tags/)

        ## Example Usage

        ```python
        import pulumi
        import pulumi_gitlab as gitlab

        example = gitlab.ProjectContainerTagProtection("example",
            project="123",
            tag_name_regex="^v[0-9]+$",
            immutable=True)
        protected = gitlab.ProjectContainerTagProtection("protected",
            project="123",
            tag_name_regex="^v[0-9]+\\\\-rc[0-9]+$",
            minimum_access_level_for_push="MAINTAINER",
            minimum_access_level_for_delete="OWNER")
        ```

        ## Import

        Starting in Terraform v1.5.0, you can use an import block to import `ProjectContainerTagProtection`. For example:

        Importing using the CLI is supported with the following syntax:

        GitLab project container tag protection rules can be imported using an id made up of `<project_id>:<protection_rule_id>`, for example:

        ```sh
        $ pulumi import gitlab:index/projectContainerTagProtection:ProjectContainerTagProtection example 123:456
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] immutable: Whether the container tag is immutable. If set, the container tag cannot be deleted or overwritten. Conflicts with `minimum_access_level_for_push` and `minimum_access_level_for_delete`.
        :param pulumi.Input[_builtins.str] minimum_access_level_for_delete: Minimum GitLab access level required to delete protected container tags in the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        :param pulumi.Input[_builtins.str] minimum_access_level_for_push: Minimum GitLab access level required to push protected container tags to the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        :param pulumi.Input[_builtins.str] project: ID or URL-encoded path of the project.
        :param pulumi.Input[_builtins.str] tag_name_regex: Container tag path pattern protected by the protection rule. Wildcard character * allowed. Tag path pattern should start with the project's full path.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProjectContainerTagProtectionArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The `ProjectContainerTagProtection` resource allows managing the lifecycle of a container tag protection rule.

        You can use a regular expression to protect multiple container tags with the same container protection rule.
        You have to **either set** (both options are mutually exclusive):

        - Only `immutable = true` which allows any user with `developer` role to create tags matching the regex but makes the object unchangeable once pushed ;
        - Both `minimum_access_level_for_push` and `minimum_access_level_for_delete` attributes to mark the container tag as mutable only with regards to the given access levels.

        **Upstream API**: [GitLab GraphQL API documentation](https://docs.gitlab.com/api/graphql/reference/#mutationcreatecontainerprotectiontagrule)

        **Protected tags**: [General documentation](https://docs.gitlab.com/user/packages/container_registry/protected_container_tags/)

        **Immutable tags**: [General documentation](https://docs.gitlab.com/user/packages/container_registry/immutable_container_tags/)

        ## Example Usage

        ```python
        import pulumi
        import pulumi_gitlab as gitlab

        example = gitlab.ProjectContainerTagProtection("example",
            project="123",
            tag_name_regex="^v[0-9]+$",
            immutable=True)
        protected = gitlab.ProjectContainerTagProtection("protected",
            project="123",
            tag_name_regex="^v[0-9]+\\\\-rc[0-9]+$",
            minimum_access_level_for_push="MAINTAINER",
            minimum_access_level_for_delete="OWNER")
        ```

        ## Import

        Starting in Terraform v1.5.0, you can use an import block to import `ProjectContainerTagProtection`. For example:

        Importing using the CLI is supported with the following syntax:

        GitLab project container tag protection rules can be imported using an id made up of `<project_id>:<protection_rule_id>`, for example:

        ```sh
        $ pulumi import gitlab:index/projectContainerTagProtection:ProjectContainerTagProtection example 123:456
        ```


        :param str resource_name: The name of the resource.
        :param ProjectContainerTagProtectionArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProjectContainerTagProtectionArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 immutable: Optional[pulumi.Input[_builtins.bool]] = None,
                 minimum_access_level_for_delete: Optional[pulumi.Input[_builtins.str]] = None,
                 minimum_access_level_for_push: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 tag_name_regex: Optional[pulumi.Input[_builtins.str]] = None,
                 timeouts: Optional[pulumi.Input[Union['ProjectContainerTagProtectionTimeoutsArgs', 'ProjectContainerTagProtectionTimeoutsArgsDict']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProjectContainerTagProtectionArgs.__new__(ProjectContainerTagProtectionArgs)

            __props__.__dict__["immutable"] = immutable
            __props__.__dict__["minimum_access_level_for_delete"] = minimum_access_level_for_delete
            __props__.__dict__["minimum_access_level_for_push"] = minimum_access_level_for_push
            if project is None and not opts.urn:
                raise TypeError("Missing required property 'project'")
            __props__.__dict__["project"] = project
            if tag_name_regex is None and not opts.urn:
                raise TypeError("Missing required property 'tag_name_regex'")
            __props__.__dict__["tag_name_regex"] = tag_name_regex
            __props__.__dict__["timeouts"] = timeouts
            __props__.__dict__["protection_rule_id"] = None
        super(ProjectContainerTagProtection, __self__).__init__(
            'gitlab:index/projectContainerTagProtection:ProjectContainerTagProtection',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            immutable: Optional[pulumi.Input[_builtins.bool]] = None,
            minimum_access_level_for_delete: Optional[pulumi.Input[_builtins.str]] = None,
            minimum_access_level_for_push: Optional[pulumi.Input[_builtins.str]] = None,
            project: Optional[pulumi.Input[_builtins.str]] = None,
            protection_rule_id: Optional[pulumi.Input[_builtins.int]] = None,
            tag_name_regex: Optional[pulumi.Input[_builtins.str]] = None,
            timeouts: Optional[pulumi.Input[Union['ProjectContainerTagProtectionTimeoutsArgs', 'ProjectContainerTagProtectionTimeoutsArgsDict']]] = None) -> 'ProjectContainerTagProtection':
        """
        Get an existing ProjectContainerTagProtection resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] immutable: Whether the container tag is immutable. If set, the container tag cannot be deleted or overwritten. Conflicts with `minimum_access_level_for_push` and `minimum_access_level_for_delete`.
        :param pulumi.Input[_builtins.str] minimum_access_level_for_delete: Minimum GitLab access level required to delete protected container tags in the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        :param pulumi.Input[_builtins.str] minimum_access_level_for_push: Minimum GitLab access level required to push protected container tags to the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        :param pulumi.Input[_builtins.str] project: ID or URL-encoded path of the project.
        :param pulumi.Input[_builtins.int] protection_rule_id: Unique ID of the protection rule.
        :param pulumi.Input[_builtins.str] tag_name_regex: Container tag path pattern protected by the protection rule. Wildcard character * allowed. Tag path pattern should start with the project's full path.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _ProjectContainerTagProtectionState.__new__(_ProjectContainerTagProtectionState)

        __props__.__dict__["immutable"] = immutable
        __props__.__dict__["minimum_access_level_for_delete"] = minimum_access_level_for_delete
        __props__.__dict__["minimum_access_level_for_push"] = minimum_access_level_for_push
        __props__.__dict__["project"] = project
        __props__.__dict__["protection_rule_id"] = protection_rule_id
        __props__.__dict__["tag_name_regex"] = tag_name_regex
        __props__.__dict__["timeouts"] = timeouts
        return ProjectContainerTagProtection(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def immutable(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the container tag is immutable. If set, the container tag cannot be deleted or overwritten. Conflicts with `minimum_access_level_for_push` and `minimum_access_level_for_delete`.
        """
        return pulumi.get(self, "immutable")

    @_builtins.property
    @pulumi.getter(name="minimumAccessLevelForDelete")
    def minimum_access_level_for_delete(self) -> pulumi.Output[_builtins.str]:
        """
        Minimum GitLab access level required to delete protected container tags in the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        """
        return pulumi.get(self, "minimum_access_level_for_delete")

    @_builtins.property
    @pulumi.getter(name="minimumAccessLevelForPush")
    def minimum_access_level_for_push(self) -> pulumi.Output[_builtins.str]:
        """
        Minimum GitLab access level required to push protected container tags to the container registry. Marks the container tag as protected. Valid values are: `MAINTAINER`, `OWNER`, `ADMIN`.
        """
        return pulumi.get(self, "minimum_access_level_for_push")

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Output[_builtins.str]:
        """
        ID or URL-encoded path of the project.
        """
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter(name="protectionRuleId")
    def protection_rule_id(self) -> pulumi.Output[_builtins.int]:
        """
        Unique ID of the protection rule.
        """
        return pulumi.get(self, "protection_rule_id")

    @_builtins.property
    @pulumi.getter(name="tagNameRegex")
    def tag_name_regex(self) -> pulumi.Output[_builtins.str]:
        """
        Container tag path pattern protected by the protection rule. Wildcard character * allowed. Tag path pattern should start with the project's full path.
        """
        return pulumi.get(self, "tag_name_regex")

    @_builtins.property
    @pulumi.getter
    def timeouts(self) -> pulumi.Output[Optional['outputs.ProjectContainerTagProtectionTimeouts']]:
        return pulumi.get(self, "timeouts")

