// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The `gitlab.ProjectIntegrationJenkins` resource manages the lifecycle of a project integration with Jenkins.
 *
 * **Upstream API**: [GitLab REST API docs](https://docs.gitlab.com/api/project_integrations/#jenkins)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as gitlab from "@pulumi/gitlab";
 *
 * const awesomeProject = new gitlab.Project("awesome_project", {
 *     name: "awesome_project",
 *     description: "My awesome project.",
 *     visibilityLevel: "public",
 * });
 * const jenkins = new gitlab.ProjectIntegrationJenkins("jenkins", {
 *     project: awesomeProject.id,
 *     jenkinsUrl: "http://jenkins.example.com",
 *     projectName: "my_project_name",
 * });
 * ```
 *
 * ## Import
 *
 * Starting in Terraform v1.5.0, you can use an import block to import `gitlab_project_integration_jenkins`. For example:
 *
 * terraform
 *
 * import {
 *
 *   to = gitlab_project_integration_jenkins.example
 *
 *   id = "see CLI command below for ID"
 *
 * }
 *
 * Importing using the CLI is supported with the following syntax:
 *
 * ```sh
 * $ pulumi import gitlab:index/projectIntegrationJenkins:ProjectIntegrationJenkins You can import a gitlab_project_integration_jenkins state using `<resource> <project_id>`:
 * ```
 *
 * ```sh
 * $ pulumi import gitlab:index/projectIntegrationJenkins:ProjectIntegrationJenkins jenkins 1
 * ```
 */
export class ProjectIntegrationJenkins extends pulumi.CustomResource {
    /**
     * Get an existing ProjectIntegrationJenkins resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectIntegrationJenkinsState, opts?: pulumi.CustomResourceOptions): ProjectIntegrationJenkins {
        return new ProjectIntegrationJenkins(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitlab:index/projectIntegrationJenkins:ProjectIntegrationJenkins';

    /**
     * Returns true if the given object is an instance of ProjectIntegrationJenkins.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectIntegrationJenkins {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectIntegrationJenkins.__pulumiType;
    }

    /**
     * Whether the integration is active.
     */
    declare public /*out*/ readonly active: pulumi.Output<boolean>;
    /**
     * Enable SSL verification. Defaults to `true` (enabled).
     */
    declare public readonly enableSslVerification: pulumi.Output<boolean>;
    /**
     * Jenkins URL like `http://jenkins.example.com`
     */
    declare public readonly jenkinsUrl: pulumi.Output<string>;
    /**
     * Enable notifications for merge request events.
     */
    declare public readonly mergeRequestEvents: pulumi.Output<boolean>;
    /**
     * Password for authentication with the Jenkins server, if authentication is required by the server.
     */
    declare public readonly password: pulumi.Output<string | undefined>;
    /**
     * ID of the project you want to activate integration on.
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * The URL-friendly project name. Example: `myProjectName`.
     */
    declare public readonly projectName: pulumi.Output<string>;
    /**
     * Enable notifications for push events.
     */
    declare public readonly pushEvents: pulumi.Output<boolean>;
    /**
     * Enable notifications for tag push events.
     */
    declare public readonly tagPushEvents: pulumi.Output<boolean>;
    /**
     * Username for authentication with the Jenkins server, if authentication is required by the server.
     */
    declare public readonly username: pulumi.Output<string | undefined>;

    /**
     * Create a ProjectIntegrationJenkins resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectIntegrationJenkinsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectIntegrationJenkinsArgs | ProjectIntegrationJenkinsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectIntegrationJenkinsState | undefined;
            resourceInputs["active"] = state?.active;
            resourceInputs["enableSslVerification"] = state?.enableSslVerification;
            resourceInputs["jenkinsUrl"] = state?.jenkinsUrl;
            resourceInputs["mergeRequestEvents"] = state?.mergeRequestEvents;
            resourceInputs["password"] = state?.password;
            resourceInputs["project"] = state?.project;
            resourceInputs["projectName"] = state?.projectName;
            resourceInputs["pushEvents"] = state?.pushEvents;
            resourceInputs["tagPushEvents"] = state?.tagPushEvents;
            resourceInputs["username"] = state?.username;
        } else {
            const args = argsOrState as ProjectIntegrationJenkinsArgs | undefined;
            if (args?.jenkinsUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'jenkinsUrl'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if (args?.projectName === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectName'");
            }
            resourceInputs["enableSslVerification"] = args?.enableSslVerification;
            resourceInputs["jenkinsUrl"] = args?.jenkinsUrl;
            resourceInputs["mergeRequestEvents"] = args?.mergeRequestEvents;
            resourceInputs["password"] = args?.password ? pulumi.secret(args.password) : undefined;
            resourceInputs["project"] = args?.project;
            resourceInputs["projectName"] = args?.projectName;
            resourceInputs["pushEvents"] = args?.pushEvents;
            resourceInputs["tagPushEvents"] = args?.tagPushEvents;
            resourceInputs["username"] = args?.username;
            resourceInputs["active"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["password"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ProjectIntegrationJenkins.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProjectIntegrationJenkins resources.
 */
export interface ProjectIntegrationJenkinsState {
    /**
     * Whether the integration is active.
     */
    active?: pulumi.Input<boolean>;
    /**
     * Enable SSL verification. Defaults to `true` (enabled).
     */
    enableSslVerification?: pulumi.Input<boolean>;
    /**
     * Jenkins URL like `http://jenkins.example.com`
     */
    jenkinsUrl?: pulumi.Input<string>;
    /**
     * Enable notifications for merge request events.
     */
    mergeRequestEvents?: pulumi.Input<boolean>;
    /**
     * Password for authentication with the Jenkins server, if authentication is required by the server.
     */
    password?: pulumi.Input<string>;
    /**
     * ID of the project you want to activate integration on.
     */
    project?: pulumi.Input<string>;
    /**
     * The URL-friendly project name. Example: `myProjectName`.
     */
    projectName?: pulumi.Input<string>;
    /**
     * Enable notifications for push events.
     */
    pushEvents?: pulumi.Input<boolean>;
    /**
     * Enable notifications for tag push events.
     */
    tagPushEvents?: pulumi.Input<boolean>;
    /**
     * Username for authentication with the Jenkins server, if authentication is required by the server.
     */
    username?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ProjectIntegrationJenkins resource.
 */
export interface ProjectIntegrationJenkinsArgs {
    /**
     * Enable SSL verification. Defaults to `true` (enabled).
     */
    enableSslVerification?: pulumi.Input<boolean>;
    /**
     * Jenkins URL like `http://jenkins.example.com`
     */
    jenkinsUrl: pulumi.Input<string>;
    /**
     * Enable notifications for merge request events.
     */
    mergeRequestEvents?: pulumi.Input<boolean>;
    /**
     * Password for authentication with the Jenkins server, if authentication is required by the server.
     */
    password?: pulumi.Input<string>;
    /**
     * ID of the project you want to activate integration on.
     */
    project: pulumi.Input<string>;
    /**
     * The URL-friendly project name. Example: `myProjectName`.
     */
    projectName: pulumi.Input<string>;
    /**
     * Enable notifications for push events.
     */
    pushEvents?: pulumi.Input<boolean>;
    /**
     * Enable notifications for tag push events.
     */
    tagPushEvents?: pulumi.Input<boolean>;
    /**
     * Username for authentication with the Jenkins server, if authentication is required by the server.
     */
    username?: pulumi.Input<string>;
}
