// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The `gitlab.ProjectApprovalRules` resource manages the complete set of approval rules of a project.
 *
 * > This resource requires a GitLab Enterprise instance.
 *
 * > This resource is authoritative: it manages the *entire* set of a project's approval rules. Any approval
 * rule that exists on the project but is not declared in the configuration will be **deleted**, and such deletions
 * are shown in the plan. If you only need to manage individual rules additively, use the
 * `gitlab.ProjectApprovalRule` resource instead.
 *
 * > **Managing the `anyApprover` rule.** A project may have **at most one** rule with
 * `ruleType = "anyApprover"` (the "all eligible users" rule), and GitLab does not require it to carry
 * any particular name. This resource therefore matches it by `ruleType` rather than by name, so its
 * name can be chosen freely. A newly created project has no approval rules at all; if you do not declare an
 * `anyApprover` rule, none is created, and one that already exists is deleted like any other undeclared
 * rule.
 *
 * > Conflicts with the use of `gitlab.ProjectApprovalRule` when used on the same project. Use one or the other to ensure the desired state.
 *
 * **Upstream API**: [GitLab REST API docs](https://docs.gitlab.com/api/merge_request_approvals/#approval-rules-for-projects)
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as gitlab from "@pulumi/gitlab";
 *
 * // This resource is authoritative: it manages the *complete* set of a project's approval rules.
 * // Any approval rule that exists on the project but is not declared below is deleted.
 * const example = new gitlab.ProjectApprovalRules("example", {
 *     project: "42",
 *     approvalRules: [
 *         {
 *             name: "All eligible users",
 *             ruleType: "any_approver",
 *             approvalsRequired: 0,
 *         },
 *         {
 *             name: "Security",
 *             approvalsRequired: 2,
 *             ruleType: "regular",
 *             userIds: [
 *                 50,
 *                 51,
 *             ],
 *             groupIds: [60],
 *         },
 *         {
 *             name: "Release managers",
 *             approvalsRequired: 1,
 *             ruleType: "regular",
 *             groupIds: [70],
 *             appliesToAllProtectedBranches: true,
 *         },
 *         {
 *             name: "Coverage-Check",
 *             approvalsRequired: 1,
 *             ruleType: "report_approver",
 *             reportType: "code_coverage",
 *             userIds: [50],
 *         },
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * Starting in Terraform v1.5.0, you can use an import block to import `gitlab.ProjectApprovalRules`. For example:
 *
 * Importing using the CLI is supported with the following syntax:
 *
 * A project's approval rules can be imported using the project ID or full path, e.g.
 *
 * ```sh
 * $ pulumi import gitlab:index/projectApprovalRules:ProjectApprovalRules example "42"
 * ```
 *
 * or
 *
 * ```sh
 * $ pulumi import gitlab:index/projectApprovalRules:ProjectApprovalRules example "my-group/my-project"
 * ```
 */
export class ProjectApprovalRules extends pulumi.CustomResource {
    /**
     * Get an existing ProjectApprovalRules resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectApprovalRulesState, opts?: pulumi.CustomResourceOptions): ProjectApprovalRules {
        return new ProjectApprovalRules(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gitlab:index/projectApprovalRules:ProjectApprovalRules';

    /**
     * Returns true if the given object is an instance of ProjectApprovalRules.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectApprovalRules {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectApprovalRules.__pulumiType;
    }

    /**
     * The complete set of approval rules of the project. Declaring an empty set removes every approval rule from the project.
     */
    declare public readonly approvalRules: pulumi.Output<outputs.ProjectApprovalRulesApprovalRule[]>;
    /**
     * The ID or full path of the project.
     */
    declare public readonly project: pulumi.Output<string>;

    /**
     * Create a ProjectApprovalRules resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectApprovalRulesArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectApprovalRulesArgs | ProjectApprovalRulesState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectApprovalRulesState | undefined;
            resourceInputs["approvalRules"] = state?.approvalRules;
            resourceInputs["project"] = state?.project;
        } else {
            const args = argsOrState as ProjectApprovalRulesArgs | undefined;
            if (args?.approvalRules === undefined && !opts.urn) {
                throw new Error("Missing required property 'approvalRules'");
            }
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            resourceInputs["approvalRules"] = args?.approvalRules;
            resourceInputs["project"] = args?.project;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectApprovalRules.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProjectApprovalRules resources.
 */
export interface ProjectApprovalRulesState {
    /**
     * The complete set of approval rules of the project. Declaring an empty set removes every approval rule from the project.
     */
    approvalRules?: pulumi.Input<pulumi.Input<inputs.ProjectApprovalRulesApprovalRule>[] | undefined>;
    /**
     * The ID or full path of the project.
     */
    project?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProjectApprovalRules resource.
 */
export interface ProjectApprovalRulesArgs {
    /**
     * The complete set of approval rules of the project. Declaring an empty set removes every approval rule from the project.
     */
    approvalRules: pulumi.Input<pulumi.Input<inputs.ProjectApprovalRulesApprovalRule>[]>;
    /**
     * The ID or full path of the project.
     */
    project: pulumi.Input<string>;
}
